Fix createRouter argument type.
types/npm-express pull request #11
Opened 2016-09-21 18:12 UTC by yasuhiroki

This PR provides for be able to add options object to `express.Router()` argument.
ex) `express.Router({caseSensitive: true})`.
Express API Doc: [express.Router options object](https://expressjs.com/en/4x/api.html#express).

2016-09-21 18:22 UTC, felixfbecker commented
I don't see this options parameter mentioned anywhere in the documentation you linked?

2016-09-21 18:24 UTC, yasuhiroki commented
@felixfbecker Sorry, I mistake link,
Would you see https://expressjs.com/en/4x/api.html#express.router ?

2016-09-21 18:44 UTC, felixfbecker commented on lib/router/index.d.ts
> +declare function createRouter(options?: {caseSensitive?: boolean; mergeParams?: boolean; strict?: boolean}): createRouter.Router;
Please put this in an interface that is exported

2016-09-21 18:45 UTC, felixfbecker requested changes
Alright. Please see comment. Also, a test for this would be nice.

2016-09-22 03:13 UTC, yasuhiroki commented on lib/router/index.d.ts
> +declare function createRouter(options?: {caseSensitive?: boolean; mergeParams?: boolean; strict?: boolean}): createRouter.Router;
OK, I added interface.

2016-09-22 03:38 UTC, yasuhiroki commented
Thank you for your comment.
I add test `router-options.ts`. Or should I add test in route.ts instead of using new file?

2016-09-22 10:24 UTC, felixfbecker commented on lib/router/index.d.ts
> +    export interface Options {
Please name this `RouterOptions`, and export it also (as a type alias) in the index file.

2016-09-22 10:24 UTC, felixfbecker requested changes
Still needs a test

2016-09-22 14:15 UTC, yasuhiroki commented on lib/router/index.d.ts
> +    export interface Options {
I changed name and expose RouterOptions.

2016-09-22 14:17 UTC, yasuhiroki commented
I changed interface name. Is this OK?

2016-09-22 14:44 UTC, felixfbecker approved these changes

2016-09-22 14:45 UTC, merged

2016-09-22 16:06 UTC, yasuhiroki commented
Thank you so much for merging!

2016-09-22 16:14 UTC, felixfbecker commented
Thank you so much for improving ❤️